### ISSUE TITLE
mp_categories_mapping

### ISSUE THREAD

**Issue by CGuangyan-BIT** [ybgdgh/L3MVN#10]
Hello, I'm very interested in your work, and there's one thing I'd like to ask about. Could you please explain how the 'mp_categories_mapping' in 'constant.py' and its corresponding 'hm3d_category' are obtained? Can you provide all the mapping relationships?

**Comment by ybgdgh** [comment]
Thanks for your interest. You can find this mapping from their dataset website: https://github.com/niessner/Matterport/blob/master/metadata/mpcat40.tsv

**Comment by CGuangyan-BIT** [comment]
thank you!
