### ISSUE TITLE
Transformers version?

### ISSUE THREAD

**Issue by Acytoo** [ybgdgh/L3MVN#2]
Hi, could you please specify the version of transformers that is compatible with this repo?

**Comment by leyuan-sun** [comment]
FYI, I used transformers              4.28.1

**Comment by Acytoo** [comment]
Thank you.

**Comment by leyuan-sun** [comment]
@Acytoo Did you run this repo. successfully?

**Comment by Acytoo** [comment]
> @Acytoo Did you run this repo. successfully?

@rginjapan  Yes.

**Comment by leyuan-sun** [comment]
@Acytoo thanks for your reply, could you plz check my submitted issue related to the dataset folder, if possible could you give me some guidance?
